<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Hex Inspect Panel</string>
	</array>
	<key>keyEquivalent</key>
	<string>~^I</string>
	<key>name</key>
	<string>hex-inspect</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([\w\-]+)\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.key.inspect</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.punctuation.inspect</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\d\-\w]+)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>data.inspect</string>
				</dict>
			</dict>
			<key>name</key>
			<string>item.inspect</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*[\w\-\s]+)\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.title.inspect</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.title-punctuation.inspect</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>item.inspect</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\w\s]+</string>
					<key>name</key>
					<string>title-info.inspect</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.inspect</string>
	<key>uuid</key>
	<string>09EC98C6-07F7-11E1-A158-A7C14724019B</string>
</dict>
</plist>
